### ISSUE TITLE
No MultiFormat Readers were able to detect the code.

### ISSUE THREAD

**Issue by drophit** [mebjas/html5-qrcode#320]
Using your demo and any bard code (all but the QR) for version 2.0.13 getting this error

No MultiFormat Readers were able to detect the code.

https://blog.minhazav.dev/QR-and-barcode-scanner-using-html-and-javascript/ 

file upload and see error

**Comment by IlhamriSKY** [comment]
I have the same issue,
![WhatsApp Image 2021-11-01 at 09 03 12 (1)](https://user-images.githubusercontent.com/18723904/139612187-157f680c-cc32-40cd-a4c1-e859b67b66c7.jpeg)

I am using Version 2.1.12
And this how i using it

```
    {!! HTML::script('assets/js/as/html5-qrcode.min.js') !!}
    <script>
        var url = '{{ route('entry.building.card', ['userid', 'reportid', 'tokenbuliding', 'lastlogin', 'session']) }}';

        var token = '{{$session}}';

        url = url.replace('userid', {{$userid}}).replace('reportid', {{$resportid}}).replace('session', token).replace('lastlogin', {{$lastlogin}});

        function docReady(fn) {
            // see if DOM is already available
            if (document.readyState === "complete"
                || document.readyState === "interactive") {
                // call on next available tick
                setTimeout(fn, 1);
            } else {
                document.addEventListener("DOMContentLoaded", fn);
            }
        }

        docReady(function () {
            var resultContainer = document.getElementById('qr-reader-results');
            var lastResult, countResults = 0;
            function onScanSuccess(decodedText, decodedResult) {
                if (decodedText !== lastResult) {
                    ++countResults;
                    lastResult = decodedText;
                    // console.log(`Scan result ${decodedText}`, decodedResult);
                    console.log(decodedText);
                    window.location.href = url.replace('tokenbuliding', decodedText);
                    html5QrcodeScanner.clear();
                }
            }

            var html5QrcodeScanner = new Html5QrcodeScanner(
                "qr-reader", { fps: 10, qrbox: {width: 250, height: 250}, aspectRatio: 1 });
            html5QrcodeScanner.render(onScanSuccess);
        });
    </script>
```

**Comment by vishakha-simply** [comment]
facing the same issue, has this been resolved @mebjas

**Comment by shadeeka** [comment]
facing same issue with version 2.1.2
this is how i use it
`htmlCamera() {
    this.html5QrcodeScanner = new Html5QrcodeScanner('qr-reader', { fps: 10, qrbox: { width: 250, height: 250 }}, false);
    this.html5QrcodeScanner.render(this.onScanSuccess);
  }

  onScanSuccess(decodedText, decodedResult) {
    console.log(`MATCH = ${decodedText}`, decodedResult);
  }`

stacktrace
`Error: Uncaught (in promise): NotFoundException: No MultiFormat Readers were able to detect the code.
NotFoundException: No MultiFormat Readers were able to detect the code.
    at MultiFormatReader.decodeInternal (http://localhost:8100/build/0.js:22614:19)
    at MultiFormatReader.decode (http://localhost:8100/build/0.js:22504:25)
    at ZXingHtml5QrcodeDecoder.webpackJsonp.979.ZXingHtml5QrcodeDecoder.decode (http://localhost:8100/build/0.js:1720:35)
    at http://localhost:8100/build/0.js:1709:31
    at new t (http://localhost:8100/build/polyfills.js:3:21506)
    at ZXingHtml5QrcodeDecoder.webpackJsonp.979.ZXingHtml5QrcodeDecoder.decodeAsync (http://localhost:8100/build/0.js:1707:16)
    at Html5QrcodeShim.webpackJsonp.978.Html5QrcodeShim.decodeAsync (http://localhost:8100/build/0.js:1618:29)
    at Html5Qrcode.webpackJsonp.966.Html5Qrcode.scanContext (http://localhost:8100/build/0.js:899:28)
    at Html5Qrcode.webpackJsonp.966.Html5Qrcode.foreverScan (http://localhost:8100/build/0.js:935:14)
    at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (http://localhost:8100/build/0.js:966:27)
    at c (http://localhost:8100/build/polyfills.js:3:19752)`

**Comment by troyanskiy** [comment]
Hello @mebjas 

Any news on that issue?
I'm having the same error on latest 2.1.3 version.

Code:
``` typescript
this.html5QrcodeScanner = new Html5Qrcode(
      'barCodeReader',
      {
        verbose: true,
        formatsToSupport: [
          Html5QrcodeSupportedFormats.CODE_128,
          Html5QrcodeSupportedFormats.CODE_39,
          Html5QrcodeSupportedFormats.EAN_8
        ]
      }
    );

    this.html5QrcodeScanner.start(
      cameraId,
      {
        fps: 10,
        qrbox: {
          width: Math.round(width * 0.8),
          height: Math.round(width * 0.5),
        },
        videoConstraints: {
          advanced: [
            {
              deviceId: cameraId,
              width,
              height
            }
          ]
        }
      },
      onScanSuccess,
      onScanFailure,
    );
 ```

Stack
```
core.js:15724 ERROR TypeError: this.decoder.decodeAsync(...).finally is not a function
    at Html5QrcodeShim.webpackJsonp.745.Html5QrcodeShim.decodeAsync (code-decoder.js:20)
    at Html5Qrcode.webpackJsonp.730.Html5Qrcode.scanContext (html5-qrcode.js:574)
    at Html5Qrcode.webpackJsonp.730.Html5Qrcode.foreverScan (html5-qrcode.js:610)
    at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (html5-qrcode.js:641)
    at HTMLVideoElement.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:17290)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
defaultErrorLogger @ core.js:15724
ErrorHandler.handleError @ core.js:15772
IonicErrorHandler.handleError @ ionic-error-handler.js:61
next @ core.js:17771
schedulerFn @ core.js:13515
SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
SafeSubscriber.next @ Subscriber.js:133
Subscriber._next @ Subscriber.js:77
Subscriber.next @ Subscriber.js:54
Subject.next @ Subject.js:47
EventEmitter.emit @ core.js:13499
(anonymous) @ core.js:17321
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
NgZone.runOutsideAngular @ core.js:17258
onHandleError @ core.js:17321
t.handleError @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
core.js:15724 ERROR Error: Uncaught (in promise): NotFoundException: No MultiFormat Readers were able to detect the code.
NotFoundException: No MultiFormat Readers were able to detect the code.
    at MultiFormatReader.decodeInternal (zxing-js.umd.js:20852)
    at MultiFormatReader.decode (zxing-js.umd.js:20742)
    at ZXingHtml5QrcodeDecoder.webpackJsonp.746.ZXingHtml5QrcodeDecoder.decode (zxing-html5-qrcode-decoder.js:65)
    at zxing-html5-qrcode-decoder.js:54
    at new t (polyfills.js:3)
    at ZXingHtml5QrcodeDecoder.webpackJsonp.746.ZXingHtml5QrcodeDecoder.decodeAsync (zxing-html5-qrcode-decoder.js:52)
    at Html5QrcodeShim.webpackJsonp.745.Html5QrcodeShim.decodeAsync (code-decoder.js:20)
    at Html5Qrcode.webpackJsonp.730.Html5Qrcode.scanContext (html5-qrcode.js:574)
    at Html5Qrcode.webpackJsonp.730.Html5Qrcode.foreverScan (html5-qrcode.js:610)
    at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (html5-qrcode.js:641)
    at c (polyfills.js:3)
    at polyfills.js:3
    at zxing-html5-qrcode-decoder.js:57
    at new t (polyfills.js:3)
    at ZXingHtml5QrcodeDecoder.webpackJsonp.746.ZXingHtml5QrcodeDecoder.decodeAsync (zxing-html5-qrcode-decoder.js:52)
    at Html5QrcodeShim.webpackJsonp.745.Html5QrcodeShim.decodeAsync (code-decoder.js:20)
    at Html5Qrcode.webpackJsonp.730.Html5Qrcode.scanContext (html5-qrcode.js:574)
    at Html5Qrcode.webpackJsonp.730.Html5Qrcode.foreverScan (html5-qrcode.js:610)
    at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (html5-qrcode.js:641)
    at HTMLVideoElement.H (polyfills.js:3)
```

**Comment by hoangtrucit** [comment]
I have the same issue when I use with `webpack`

**Comment by ntrannghia** [comment]
Hi @mebjas, I'm also face to this issue in version 2.2.0 too

> Hello @mebjas
> 
> Any news on that issue? I'm having the same error on latest 2.1.3 version.
> 
> Code:
> 
> ```ts
> this.html5QrcodeScanner = new Html5Qrcode(
>       'barCodeReader',
>       {
>         verbose: true,
>         formatsToSupport: [
>           Html5QrcodeSupportedFormats.CODE_128,
>           Html5QrcodeSupportedFormats.CODE_39,
>           Html5QrcodeSupportedFormats.EAN_8
>         ]
>       }
>     );
> 
>     this.html5QrcodeScanner.start(
>       cameraId,
>       {
>         fps: 10,
>         qrbox: {
>           width: Math.round(width * 0.8),
>           height: Math.round(width * 0.5),
>         },
>         videoConstraints: {
>           advanced: [
>             {
>               deviceId: cameraId,
>               width,
>               height
>             }
>           ]
>         }
>       },
>       onScanSuccess,
>       onScanFailure,
>     );
> ```
> 
> Stack
> 
> ```
> core.js:15724 ERROR TypeError: this.decoder.decodeAsync(...).finally is not a function
>     at Html5QrcodeShim.webpackJsonp.745.Html5QrcodeShim.decodeAsync (code-decoder.js:20)
>     at Html5Qrcode.webpackJsonp.730.Html5Qrcode.scanContext (html5-qrcode.js:574)
>     at Html5Qrcode.webpackJsonp.730.Html5Qrcode.foreverScan (html5-qrcode.js:610)
>     at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (html5-qrcode.js:641)
>     at HTMLVideoElement.H (polyfills.js:3)
>     at t.invokeTask (polyfills.js:3)
>     at Object.onInvokeTask (core.js:17290)
>     at t.invokeTask (polyfills.js:3)
>     at r.runTask (polyfills.js:3)
>     at e.invokeTask [as invoke] (polyfills.js:3)
> defaultErrorLogger @ core.js:15724
> ErrorHandler.handleError @ core.js:15772
> IonicErrorHandler.handleError @ ionic-error-handler.js:61
> next @ core.js:17771
> schedulerFn @ core.js:13515
> SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
> SafeSubscriber.next @ Subscriber.js:133
> Subscriber._next @ Subscriber.js:77
> Subscriber.next @ Subscriber.js:54
> Subject.next @ Subject.js:47
> EventEmitter.emit @ core.js:13499
> (anonymous) @ core.js:17321
> t.invoke @ polyfills.js:3
> r.run @ polyfills.js:3
> NgZone.runOutsideAngular @ core.js:17258
> onHandleError @ core.js:17321
> t.handleError @ polyfills.js:3
> r.runTask @ polyfills.js:3
> e.invokeTask @ polyfills.js:3
> p @ polyfills.js:2
> v @ polyfills.js:2
> core.js:15724 ERROR Error: Uncaught (in promise): NotFoundException: No MultiFormat Readers were able to detect the code.
> NotFoundException: No MultiFormat Readers were able to detect the code.
>     at MultiFormatReader.decodeInternal (zxing-js.umd.js:20852)
>     at MultiFormatReader.decode (zxing-js.umd.js:20742)
>     at ZXingHtml5QrcodeDecoder.webpackJsonp.746.ZXingHtml5QrcodeDecoder.decode (zxing-html5-qrcode-decoder.js:65)
>     at zxing-html5-qrcode-decoder.js:54
>     at new t (polyfills.js:3)
>     at ZXingHtml5QrcodeDecoder.webpackJsonp.746.ZXingHtml5QrcodeDecoder.decodeAsync (zxing-html5-qrcode-decoder.js:52)
>     at Html5QrcodeShim.webpackJsonp.745.Html5QrcodeShim.decodeAsync (code-decoder.js:20)
>     at Html5Qrcode.webpackJsonp.730.Html5Qrcode.scanContext (html5-qrcode.js:574)
>     at Html5Qrcode.webpackJsonp.730.Html5Qrcode.foreverScan (html5-qrcode.js:610)
>     at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (html5-qrcode.js:641)
>     at c (polyfills.js:3)
>     at polyfills.js:3
>     at zxing-html5-qrcode-decoder.js:57
>     at new t (polyfills.js:3)
>     at ZXingHtml5QrcodeDecoder.webpackJsonp.746.ZXingHtml5QrcodeDecoder.decodeAsync (zxing-html5-qrcode-decoder.js:52)
>     at Html5QrcodeShim.webpackJsonp.745.Html5QrcodeShim.decodeAsync (code-decoder.js:20)
>     at Html5Qrcode.webpackJsonp.730.Html5Qrcode.scanContext (html5-qrcode.js:574)
>     at Html5Qrcode.webpackJsonp.730.Html5Qrcode.foreverScan (html5-qrcode.js:610)
>     at HTMLVideoElement.videoElement.onplaying [as __zone_symbol__ON_PROPERTYplaying] (html5-qrcode.js:641)
>     at HTMLVideoElement.H (polyfills.js:3)
> ```

**Comment by halo** [comment]
For me, this error depends on the video width and height. If I do not restrict the video size, it reliably detects all codes without delay. If I fit the video into a div that has width and height set via CSS, then I cannot detect the codes, even though nothing else changed.

See also https://github.com/mebjas/html5-qrcode/issues/415#issuecomment-1045987442

**Comment by philip247** [comment]
Even your own example does not work.
[https://zxing-js.github.io/library/examples/multi-image/](https://zxing-js.github.io/library/examples/multi-image/)

**Comment by Dev-Dolphin** [comment]
I have the same issue when I use upload file @mebjas (last version)

**Comment by jb1232312** [comment]
when i put a logo design in my qr code the qr code reader is not working it's say D: No MultiFormat Readers were able to detect the code.

**Comment by gremo** [comment]
Same issue here using Webpack... any workaround?

**Comment by zoernert** [comment]
I have the same issue in my code with the "No MultiFormat Readers werre able to detect the code". But... It only happens if I upload the image like:
![Download (42)](https://github.com/user-attachments/assets/4f38d733-8d3a-4d29-abbb-722e01358cff)

If I use the camera of my device(s) it works. Reproducible on https://scanapp.org/.

The fun part is - that the same code to generate and save the QR code works with HTML5-QRCode sometimes (~50%). So I think in my case it has something todo with the generation of the QR code itself.

**Comment by Lordbufu** [comment]
Same problem here, regardless of how 'good' the image is (i tried loads with a variation of quality, and even used stabalizers).

The version i used is the current most updated minimized JS version  (April 15 2023).

The images used  are the following (also tested/replicated) in the scanapp example site), where the first is working and the second is not:
![working](https://github.com/user-attachments/assets/074b815e-aede-4a6f-ab4b-d22709966dc3)
![notWorking](https://github.com/user-attachments/assets/24f66de2-8443-45f4-9abe-5147864caece)

The code used is very basic, as i have not moved passed templating and testing yet:
```
// Triggered via a onreadystatechange in my main code, non-relevant code was removed obviously.
function initBeheer() {
	html5QrcodeScanner = new Html5QrcodeScanner( "reader", { fps: 10 } );
	html5QrcodeScanner.render( onScanSuccess, onScanError );
}
	
function onScanSuccess( decodedText, decodedResult ) {
	formatName = decodedResult["result"]["format"]["formatName"];

        // Add decoded text to hidden form input.
	document.getElementById("albumS-form-isbn").value = decodedText;
	html5QrcodeScanner.clear();

	// Here i would submit the form to PhP for further processing, uncommented for troubleshooting.
	// document.getElementById("modal-form-scan").submit();

	console.log(decodedText);
	console.log(decodedResult);
}

function onScanError( errorMessage ) { console.log( errorMessage ); }
```

No errors on load, the default interface works, and all buttons work as expected.

When using a image, the error is console logged is the following (similar to the verbose error, minus the upscale info):
```
	D: No MultiFormat Readers were able to detect the code.
		at lr.decodeInternal (https://localhost/js/html5-qrcode.min.js:1:253484)
		at lr.decode (https://localhost/js/html5-qrcode.min.js:1:252382)
		at e.decode (https://localhost/js/html5-qrcode.min.js:1:299459)
		at https://localhost/js/html5-qrcode.min.js:1:299248
		at new Promise (<anonymous>)
		at e.decodeAsync (https://localhost/js/html5-qrcode.min.js:1:299213)
		at t.<anonymous> (https://localhost/js/html5-qrcode.min.js:1:305832)
		at https://localhost/js/html5-qrcode.min.js:1:304845
		at Object.next (https://localhost/js/html5-qrcode.min.js:1:304950)
		at https://localhost/js/html5-qrcode.min.js:1:303865
```

I hope this helps, though reading some replies, it seems like the issue causing it is known already just not solved / correctly ¿
Obvious the camera scanner works on these with no issues, its only images/photo's that it struggles with.

Kr

**Comment by ansarikhurshid786** [comment]
facing same issue. any solution ?

**Comment by JanbertCampos** [comment]
it's already been 4 years this issue was not yet resolved

**Comment by ROBERT-MCDOWELL** [comment]
@JanbertCampos 
rather than wait 4 years for the issue to be solved, why not you try to learn how to solve your issue?
git repo are open source, meaning that everyone can contribute and solve the issues, if you wish a software with support so go to buy one and you will have technical and bug support.

**Comment by justconsult-dev** [comment]
Maybe Duplicating #960

**Comment by matheuscsant** [comment]
In my case, I'm using scalajs with laminar, I was having this same error, but the problem was that I hadn't set a size on the div, after setting the size, it solved my problem.

> I'm using webcam to read QRCode

Example of what my code looked like

**page.scala**
```scala
class TestPageView {

  def el: HtmlElement = {
    
    var html5QrCode: Option[Html5Qrcode] = Option.empty
    var mediaStream: Option[MediaStream] = Option.empty
    val mediaConstraints = new dom.MediaStreamConstraints {
      video = true
    }

    // Observer to start scan
    val startScanning: Observer[Unit] = Observer { _ =>
      val config = js.Dynamic.literal(
        fps = 1,
        qrbox = 250
      )

      dom.window.navigator.mediaDevices.enumerateDevices().toFuture.foreach { devices =>
        val videoInputs = devices.filter(_.kind == "videoinput")
        videoInputs.foreach(device => dom.console.info(s"Camera found: ${device.deviceId} - ${device.label}"))
        val cameraId = videoInputs.headOption.map(_.deviceId).getOrElse("")
        if (cameraId.isEmpty) {
          dom.console.info("No camera found or available!")
        } else {
          dom.console.info(s"Trying to use camera id - $cameraId")
          html5QrCode = Option(new Html5Qrcode("test2"))
          html5QrCode.get.start(
            "cd721c4275fb609407677430985bda97225b0ea852f2e34163ce4202842f66a0",
            config,
            qrCode => dom.console.info(s"Code readed: $qrCode"),
            error  => dom.console.error(s"Error reading: $error")
          ).toFuture.onComplete {
            case scala.util.Success(_) =>
              dom.console.info("QR Code scanner started successfully.")
            case scala.util.Failure(exception) =>
              dom.console.error(s"Failed to start QR Code scanner: ${exception.getMessage}")
          }
        }
      }
    }
    
    def startCamera() = {
      // Request to open camera
      navigator.mediaDevices.getUserMedia(constraints = mediaConstraints)
        .toFuture
        .foreach { stream =>
          mediaStream = Some(stream)
          dom.console.info("Starting camera")
          startScanning.onNext(())
        }
    }

    def stopCamera() = {
      // Request to close camera
      if (mediaStream.isDefined) {
        mediaStream.get.getTracks().foreach(_.stop())
        mediaStream = Option.empty
        dom.console.info("Stopping camera")
        html5QrCode.get.stop()
      }
    }

    def qrcodeTest: HtmlElement =
      div(
        cls("flex flex-col max-w-80 border p m-4 gap-4"),
        button(cls("btn"), "Start camera"      , onClick --> startCamera()),
        button(cls("btn"), "Stop camera"       , onClick --> stopCamera()),
      )

    div(
      h1("Test Page"),
      div(cls("flex flex-row content-center"),
        qrcodeTest,
        div(idAttr := "test2", cls := "w-96 h-96")
      )
    )

  }
}
```

**qrcode.scala**
```scala
@js.native
@JSImport("html5-qrcode", "Html5Qrcode")
class Html5Qrcode(scannerId: String) extends js.Object {
  def start(
    cameraId: String,
    config: js.UndefOr[js.Object],
    qrCodeSuccessCallback: js.Function1[String, Unit],
    qrCodeErrorCallback: js.UndefOr[js.Function1[js.Any, Unit]]
  ): js.Promise[Unit] = js.native

  def stop(): js.Promise[Unit] = js.native
}
```

**Result**
![image](https://github.com/user-attachments/assets/c719b725-9f86-4ee8-b1a5-16a9aa558ad8)
![image](https://github.com/user-attachments/assets/4ee6097e-7ee8-402e-a3bb-8512423d4aa5)
In my case, when this exception is thrown, it just means that it couldn't find the qrcode

**Comment by robizzt** [comment]
I tried my "low quality" images on latest version, same problem. Tried with @Lordbufu  images, still the same problem.

I downgraded to the version 2.3.3; my images did not work, but @Lordbufu images (high quality) worked!

So from v2.3.4, the problem is the same on all images.

Note: I'm using `.scanFile` method, and same problem is on https://scanapp.org/

**Comment by egavelar** [comment]
Hello, 

I've got the same problem using Passbolt on version 5.0.0, when adding some Microsoft QR Codes.
My workaround for now is to enlarge/reduce the image, or use zbarimg to get the string of the TOTP code.

**Comment by dopreo** [comment]
Still seem to be experiencing this; would appreciate any advice.
