### ISSUE TITLE
Rails + Stimulus + Importmaps fails to render Html5QrcodeScanner

### ISSUE THREAD

**Issue by sevos** [mebjas/html5-qrcode#687]
**Describe the bug**
When calling render on the Html5QrcodeScanner I get the following error

```
TypeError: Cannot read properties of undefined (reading 'QR_CODE')
    at new ZXingHtml5QrcodeDecoder (zxing-html5-qrcode-decoder.js:6:71)
    at new Html5QrcodeShim (code-decoder.js:49:37)
    at new Html5Qrcode (html5-qrcode.js:104:23)
    at Html5QrcodeScanner.render (html5-qrcode-scanner.js:87:28)
    at extended.connect (controller-e951e35ab1deea099074ac4e0dd3fb1297e32bea9a496fd483513a7ba41650c3.js:37:20)
    at Context.connect (stimulus.js? [sm]:1379:29)
    at Module.connectContextForScope (stimulus.js? [sm]:1549:17)
    at stimulus.js? [sm]:1936:42
    at Array.forEach (<anonymous>)
    at Router.connectModule (stimulus.js? [sm]:1936:16)
```

**To Reproduce**
1. Fresh Ruby on Rails 7.0.4 app using import maps
2. Following the README, adding triggers in the Stimulus controller in the `#connect` method
3. Configuration in the `importmap.rb` file (which defines where to load particular library from):

```
pin "html5-qrcode", to: "https://ga.jspm.io/npm:html5-qrcode@2.3.4/esm/index.js"
```

**Expected behavior**
I am just trying to follow the examples from the README. I expect the component to show the video feed and start scanning, like in the demo.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version 109.0.5414.119

Please let me know if I can help debug this.

**Comment by sevos** [comment]
The solution was to change the pin to use CJS:

```
pin "html5-qrcode", to: "https://ga.jspm.io/npm:html5-qrcode@2.3.4/cjs/index.js"
```
